using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebAppAngular.Models;

namespace WebAppAngular.Controllers
{
    public class DemoController : Controller
    {
        // GET: Demo
        [HttpGet]
        public JsonResult PersonsList()
        {
            List<Person> items = new List<Person>
            {

                new Person { first_name="Rebbecca",last_name="Didio",company_name="Landrum Temporary Services",address="534 Schoenborn St #51",city="Talmalmo",state="NS"},
                new Person { first_name="Stevie",last_name="Hallo",company_name="Inabinet, Macre Esq",address="69206 Jackson Ave",city="Lane Cove",state="WA"},
                new Person { first_name="Mariko",last_name="Stayer",company_name="Morris Downing & Sherred",address="808 Glen Cove Ave",city="Cartmeticup",state="WA"},
                new Person { first_name="Gerardo",last_name="Woodka",company_name="Buelt, David L Esq",address="373 Lafayette St",city="Nyamup",state="NS"},
                new Person { first_name="Mayra",last_name="Bena",company_name="Artesian Ice & Cold Storage Co",address="87 Sylvan Ave",city="Bendick Murrell",state="QL"},
                new Person { first_name="Idella",last_name="Scotland",company_name="Midway Hotel",address="60562 Ky Rt 321",city="Purrawunda",state="SA"},
                new Person { first_name="Sherill",last_name="Klar",company_name="Selsor, Robert J Esq",address="70 S 18th Pl",city="Blanchetown",state="QL"},
                new Person { first_name="Ena",last_name="Desjardiws",company_name="Vincent J Petti & Co",address="8839 Ventura Blvd",city="Rockside",state="TA"},
                new Person { first_name="Vince",last_name="Siena",company_name="Prentiss, Paul F Esq",address="3684 N Wacker Dr",city="Rosegarland",state="QL"},
                new Person { first_name="Theron",last_name="Jarding",company_name="Public Works Department",address="68828 S 32nd St #6",city="Ringwood",state="WA"},
                new Person { first_name="Amira",last_name="Chudej",company_name="Prudential Lighting Corp",address="43157 Cypress St",city="Maylands",state="QL"},
                new Person { first_name="Marica",last_name="Tarbor",company_name="Wood, J Scott Esq",address="6 S Hanover Ave",city="Wooloowin",state="NS"},
                new Person { first_name="Shawna",last_name="Albrough",company_name="Swanson Peterson Fnrl Home Inc",address="27916 Tarrytown Rd",city="Arthurville",state="QL"},
                new Person { first_name="Paulina",last_name="Maker",company_name="Old Cider Mill Grove",address="79620 Timber Dr",city="Mapleton",state="NS"},
                new Person { first_name="Rose",last_name="Jebb",company_name="Cooper Myers Y Co",address="387 Airway Cir #62",city="Tuggerawong",state="AC"},
                new Person { first_name="Reita",last_name="Tabar",company_name="Angelo International",address="570 W Pine St",city="Red Hill",state="QL"},
                new Person { first_name="Maybelle",last_name="Bewley",company_name="Blackley, William J Pa",address="823 Fishers Ln",city="Inverlaw",state="NS"},
                new Person { first_name="Camellia",last_name="Pylant",company_name="Phoenix Phototype",address="4 Brookcrest Dr #7786",city="Eugowra",state="NS"},
                new Person { first_name="Roy",last_name="Nybo",company_name="Quartzite Processing Inc",address="72 Wyoming Ave",city="Kotara Fair",state="QL"},
                new Person { first_name="Albert",last_name="Sonier",company_name="Biltmore Textile Co Inc",address="754 Sammis Ave",city="Burpengary",state="QL"},
                new Person { first_name="Hayley",last_name="Taghon",company_name="Gateway Refrigeration",address="660 N Green St",city="Ellis Beach",state="VI"},
                new Person { first_name="Norah",last_name="Daleo",company_name="Anchorage Yamaha",address="970 Waterloo Rd",city="Fish Creek",state="QL"},
                new Person { first_name="Rosina",last_name="Sidhu",company_name="Wynns Precision Inc Az Div",address="4129 Abbott Dr",city="Kennedy",state="TA"},
                new Person { first_name="Royal",last_name="Costeira",company_name="Paragon Cable Tv",address="1529 Prince Rodgers Ave",city="Cape Portland",state="QL"},
                new Person { first_name="Barrie",last_name="Nicley",company_name="Eagle Computer Services Inc",address="2 N Valley Mills Dr",city="Warra",state="NT"},
                new Person { first_name="Linsey",last_name="Gedman",company_name="Kansas Association Ins Agtts",address="50968 Kurtz St #45",city="Wanguri",state="VI"},
                new Person { first_name="Laura",last_name="Bourbonnais",company_name="Di Giacomo, Richard F Esq",address="71585 S Ayon Ave #9",city="Alvie",state="NS"},
                new Person { first_name="Fanny",last_name="Stoneking",company_name="Butler, Frank B Esq",address="8 Old County Rd #3",city="Wherrol Flat",state="QL"},
                new Person { first_name="Kristian",last_name="Ellerbusch",company_name="Alphagraphics Printshops",address="13904 S 35th St",city="Placid Hills",state="WA"},
                new Person { first_name="Gwen",last_name="Julye",company_name="Voyager Travel Service",address="6149 Kapiolani Blvd #6",city="Nedlands",state="QL"},
                new Person { first_name="Ben",last_name="Majorga",company_name="N Amer Plast & Chemls Co Inc",address="95431 34th Ave #62",city="Auchenflower",state="VI"},
                new Person { first_name="Trina",last_name="Oto",company_name="D L Downing General Contr Inc",address="25 Swift Ave",city="Buninyong",state="NS"},
                new Person { first_name="Emelda",last_name="Geffers",company_name="Community Insurance Agy Inc",address="14304 Old Alexandria Ferry Rd",city="Dangar Island",state="QL"},
                new Person { first_name="Zana",last_name="Ploszaj",company_name="House Of Ing",address="1585 Salem Church Rd #59",city="Sunny Nook",state="QL"},
                new Person { first_name="Shaun",last_name="Rael",company_name="Vei Inc",address="75962 E Drinker St",city="Minden",state="WA"},
                new Person { first_name="Oren",last_name="Lobosco",company_name="Hanna, Robert J Esq",address="8978 W Henrietta Rd",city="Tibradden",state="QL"},
                new Person { first_name="Catherin",last_name="Aguele",company_name="Design Rite Homes Inc",address="86 Worth St #272",city="Clermont",state="SA"},
                new Person { first_name="Pearlene",last_name="Boudrie",company_name="State Library",address="15 Campville Rd #191",city="Kadina",state="NS"},
                new Person { first_name="Kathryn",last_name="Bonalumi",company_name="Vista Grande Baptist Church",address="3 N Ridge Ave",city="Sawtell",state="NS"},
                new Person { first_name="Suzan",last_name="Landa",company_name="Poole Publications Inc",address="3713 Poway Rd",city="East Gosford",state="VI"},
                new Person { first_name="Sommer",last_name="Agar",company_name="Affilated Consulting Group Inc",address="1 E 17th St",city="Fosterville",state="NS"},
                new Person { first_name="Keena",last_name="Rebich",company_name="Northwestern Mutual Life Ins",address="5 Liberty Ave",city="Bateau Bay",state="QL"},
                new Person { first_name="Rupert",last_name="Hinkson",company_name="Barrett Burke Wilson Castl",address="404 Broxton Ave",city="Glenmoral",state="NS"},
                new Person { first_name="Aleta",last_name="Poarch",company_name="Helricks Inc",address="4 S Main St #285",city="Bolivia",state="VI"},
                new Person { first_name="Jamal",last_name="Korczynski",company_name="Wynn, Mary Ellen Esq",address="1255 W Passaic St #1553",city="East Melbourne",state="QL"},
                new Person { first_name="Luz",last_name="Broccoli",company_name="Mackraft Signs",address="377 Excalibur Dr",city="Taringa",state="WA"},
                new Person { first_name="Janessa",last_name="Ruthers",company_name="Ansaring Answering Service",address="7 Wilshire Blvd",city="Koolan Island",state="QL"},
                new Person { first_name="Lavonne",last_name="Esco",company_name="Joiner & Goudeau Law Offices",address="7 Hugh Wallis Rd",city="Maleny",state="WA"},
                new Person { first_name="Honey",last_name="Lymaster",company_name="Cox, J Thomas Jr",address="7177 E 14th St",city="Yelverton",state="NS"},
                new Person { first_name="Jean",last_name="Cecchinato",company_name="Bill, Michael M",address="67765 W 11th St",city="Flinders",state="NS"},
                new Person { first_name="Katlyn",last_name="Flitcroft",company_name="A B C Tank Co",address="99968 Merced St #79",city="Empire Bay",state="NS"},
                new Person { first_name="Cassie",last_name="Soros",company_name="Jolley, Mark A Cpa",address="40 E 19th Ave",city="Rose Bay North",state="VI"},
                new Person { first_name="Rolf",last_name="Gene",company_name="Melco Embroidery Systems",address="84826 Plaza Dr",city="Macks Creek",state="QL"},
                new Person { first_name="Darnell",last_name="Moothart",company_name="Witchs Brew",address="20214 W Main St",city="East Toowoomba",state="WA"},
                new Person { first_name="Cherilyn",last_name="Fraize",company_name="Funding Equity Corp",address="8039 Howard Ave",city="Bimbijy",state="NS"},
                new Person { first_name="Lynda",last_name="Lazzaro",company_name="Saturn Of Delray",address="8 Austin Bluffs Pky",city="Kundabung",state="QL"},
                new Person { first_name="Leigha",last_name="Capelli",company_name="Motel 6",address="96605 Pioneer Rd",city="Pinnacle",state="QL"},
                new Person { first_name="Delfina",last_name="Binnie",company_name="Ultimate In Womens Apparel The",address="6 Hope Rd #10",city="Watsonville",state="NS"},
                new Person { first_name="Carlota",last_name="Gephardt",company_name="Ballinger, Maria Chan Esq",address="65898 E St Nw",city="Seaforth",state="TA"},
                new Person { first_name="Alida",last_name="Helger",company_name="N E Industrial Distr Inc",address="39 Broad St",city="White Hills",state="NS"},
                new Person { first_name="Donte",last_name="Resureccion",company_name="Joondeph, Jerome J Esq",address="654 Seguine Ave",city="Bellangry",state="QL"},
                new Person { first_name="Lou",last_name="Kriner",company_name="Art In Forms",address="78 31st St",city="Ascot",state="QL"},
                new Person { first_name="Dortha",last_name="Vrieze",company_name="Central Hudson Ent Corp",address="35673 Annapolis Rd #190",city="Stafford Heights",state="NS"},
                new Person { first_name="Genevive",last_name="Sanborn",company_name="Marscher, William F Iii",address="98247 Russell Blvd",city="Bygalorie",state="NS"},
                new Person { first_name="Alease",last_name="Strawbridge",company_name="Smith, Sean O Esq",address="3 S Willow St #82",city="Boolaroo",state="QL"},
                new Person { first_name="Veda",last_name="Mishkin",company_name="Maverik Country Stores Inc",address="199 Maple Ave",city="Brookhill",state="NS"},
                new Person { first_name="Craig",last_name="Vandersloot",company_name="United Christian Cmnty Crdt Un",address="423 S Navajo St #56",city="Hillston",state="VI"},
                new Person { first_name="Lauran",last_name="Tovmasyan",company_name="Radecker, H Philip Jr",address="5 30w W #3083",city="Ivanhoe East",state="VI"},
                new Person { first_name="Aaron",last_name="Kloska",company_name="Cullen, Jack J Esq",address="57245 W Union Blvd #25",city="Caniambo",state="VI"},
                new Person { first_name="Francene",last_name="Skursky",company_name="Kszl Am Radio",address="971 Northwest Blvd",city="Myrniong",state="VI"},
                new Person { first_name="Zena",last_name="Daria",company_name="Blewett, Yvonne S",address="1089 Pacific Coast Hwy",city="Woolamai",state="WA"},
                new Person { first_name="Brigette",last_name="Breckenstein",company_name="Sheraton Inn Atlanta Northwest",address="6787 Emerson St",city="Wardering",state="WA"},
                new Person { first_name="Jeniffer",last_name="Jezek",company_name="Preston, Anne M Esq",address="8 Middletown Blvd #708",city="Kukerin",state="VI"},
                new Person { first_name="Selma",last_name="Elm",company_name="A & A Custom Rubber Stamps",address="56 Tank Farm Rd",city="Somers",state="TA"},
                new Person { first_name="Elenora",last_name="Handler",company_name="Hirsch, Walter W Esq",address="503 Fulford Ave",city="Wayatinah",state="QL"},
                new Person { first_name="Nadine",last_name="Okojie",company_name="Jones, Peter B Esq",address="8275 Calle De Industrias",city="Alligator Creek",state="QL"},
                new Person { first_name="Kristin",last_name="Shiflet",company_name="Sterling Institute",address="92 South St",city="Camp Mountain",state="QL"},
                new Person { first_name="Melinda",last_name="Fellhauer",company_name="Cross Western Store",address="56710 Euclid Ave",city="Brandy Creek",state="VI"},
                new Person { first_name="Kirby",last_name="Litherland",company_name="Demer Normann Smith Ltd",address="5210 E Airy St #2",city="Sovereign Hill",state="SA"},
                new Person { first_name="Kent",last_name="Ivans",company_name="Ny Stat Trial Lawyers Assn",address="31 Schuyler Ave",city="Arno Bay",state="VI"},
                new Person { first_name="Dan",last_name="Platz",company_name="Mann, Charles E Esq",address="661 Plummer St #963",city="Maffra",state="TA"},
                new Person { first_name="Millie",last_name="Pirkl",company_name="Airnetics Engineering Co",address="1351 Simpson St",city="Ulverstone",state="TA"},
                new Person { first_name="Moira",last_name="Qadir",company_name="American Pie Co Inc",address="2391 Pacific Blvd",city="Wattle Hill",state="SA"},
                new Person { first_name="Reta",last_name="Qazi",company_name="Brown Chiropractic",address="1886 2nd Ave",city="Bower",state="VI"},
                new Person { first_name="Brittney",last_name="Lolley",company_name="Classic Video Duplication Inc",address="52404 S Clinton Ave",city="Stonehaven",state="WA"},
                new Person { first_name="Leandro",last_name="Bolka",company_name="Mcclier Corp",address="405 W Lee St",city="East Newdegate",state="VI"},
                new Person { first_name="Edison",last_name="Sumera",company_name="Gormley Lore Murphy",address="5656 N Fiesta Blvd",city="Emerald",state="VI"},
                new Person { first_name="Breana",last_name="Cassi",company_name="Thudium Mail Advg Company",address="9 Beverly Rd #5",city="Katunga",state="SA"},
                new Person { first_name="Jarvis",last_name="Nicols",company_name="Jen E Distributing Co",address="96 Armitage Ave",city="Willunga",state="WA"},
                new Person { first_name="Felicitas",last_name="Orlinski",company_name="Re/max Realty Services",address="523 N Prince St",city="Two Rocks",state="NS"},
                new Person { first_name="Geraldine",last_name="Neisius",company_name="Roundys Pole Fence Co",address="6926 Orange Ave",city="Caldwell",state="QL"},
                new Person { first_name="Alfred",last_name="Pacleb",company_name="Chadds Ford Winery",address="6940 Prospect Pl",city="Coppabella",state="NS"},
                new Person { first_name="Leatha",last_name="Block",company_name="Barragar, Anne L Esq",address="52347 San Fernando Rd",city="Calala",state="NS"},
                new Person { first_name="Jacquelyne",last_name="Rosso",company_name="Kvoo Radio",address="5399 Mcwhorter Rd",city="Nambucca Heads",state="NS"},
                new Person { first_name="Jonelle",last_name="Epps",company_name="Donovan, William P Esq",address="7 Hall St",city="Mccullys Gap",state="QL"},
                new Person { first_name="Rosamond",last_name="Amlin",company_name="Overseas General Business Co",address="5 W Allen St",city="Toowoomba South",state="WA"},
                new Person { first_name="Johnson",last_name="Mcenery",company_name="Nilad Machining",address="15126 Goldenwest St",city="Applecross",state="VI"},
                new Person { first_name="Elliot",last_name="Scatton",company_name="Byrne, Beth Hobbs",address="94 I 55s S",city="Camberwell West",state="WA"},
                new Person { first_name="Gerri",last_name="Perra",company_name="Dileo, Lucille A Esq",address="288 N 168th Ave #266",city="North Perth",state="NS"},
                new Person { first_name="Rosendo",last_name="Jelsma",company_name="First Express",address="5 Richmond Ct",city="Coombell",state="QL"},
                new Person { first_name="Eveline",last_name="Brickhouse",company_name="Elbin Internatl Baskets",address="28 Aaronwood Ave Ne",city="Pacific Heights",state="WA"},
                new Person { first_name="Laurene",last_name="Bennett",company_name="Multiform Business Printing",address="39701 6th Ave #1485",city="Guildford",state="WA"},
                new Person { first_name="Tegan",last_name="Ebershoff",company_name="Jin Shin Travel Agency",address="35662 S University Blvd",city="Herron",state="NS"},
                new Person { first_name="Tracie",last_name="Huro",company_name="Electra Gear Divsn Regal",address="73 Dennison St #70",city="Mirrool",state="QL"},
                new Person { first_name="Mertie",last_name="Kazeck",company_name="Sparta Home Center",address="9591 Bayshore Rd #637",city="Bundaberg West",state="NS"},
                new Person { first_name="Clare",last_name="Bortignon",company_name="R A C E Enterprises Inc",address="57 N Weinbach Ave",city="Lane Cove",state="VI"},
                new Person { first_name="Rebeca",last_name="Baley",company_name="Jersey Wholesale Fence Co Inc",address="286 Santa Rosa Ave",city="Reservoir",state="QL"},
                new Person { first_name="Nilsa",last_name="Pawell",company_name="Ryan, Barry M Esq",address="446 Woodward Ave #1",city="Upper Kedron",state="VI"},
                new Person { first_name="Samuel",last_name="Arellanes",company_name="Albright, Alexandra W Esq",address="1 Jenks Ave",city="Buchan",state="SA"},
                new Person { first_name="Ivette",last_name="Servantes",company_name="Gazette Record",address="7 Valley Blvd",city="Beltana",state="SA"},
                new Person { first_name="Merrilee",last_name="Fajen",company_name="Cochnower Pest Control",address="42741 Anania Dr",city="Kingswood",state="TA"},
                new Person { first_name="Gianna",last_name="Eilers",company_name="Als Village Stationers",address="5 Shakespeare Ave",city="Nicholls Rivulet",state="QL"},
                new Person { first_name="Hyman",last_name="Phinazee",company_name="A B C Pattern & Foundry Co",address="245 5th Ave",city="Upper Mount Gravatt",state="TA"},
                new Person { first_name="Buck",last_name="Pascucci",company_name="Gaddis Court Reporting",address="2 Gateway Ctr",city="Ridgley",state="VI"},
                new Person { first_name="Kenny",last_name="Leicht",company_name="Howard Johnson",address="3175 Northwestern Hwy",city="Tubbut",state="NS"},
                new Person { first_name="Tabetha",last_name="Bai",company_name="Sunrise Cirby Animal Hospital",address="8 S Plaza Dr",city="Collingullie",state="SA"},
                new Person { first_name="Alonso",last_name="Popper",company_name="Braid Electric Co",address="8 Collins Ave",city="Munno Para",state="NS"},
                new Person { first_name="Alonzo",last_name="Polek",company_name="Lisko, Roy K Esq",address="9526 Lincoln St",city="Tyagarah",state="WA"},
                new Person { first_name="Son",last_name="Magnotta",company_name="House Of Ing",address="406 E 4th St",city="Redgate",state="VI"},
                new Person { first_name="Jesusita",last_name="Druck",company_name="Hassanein, Nesa E Esq",address="361 Via Colinas",city="Modewarre",state="WA"},
                new Person { first_name="Annice",last_name="Kunich",company_name="Frasier Karen L Kolligs",address="94 S Jefferson Rd",city="Stirling Range National Park",state="TA"},
                new Person { first_name="Delila",last_name="Buchman",company_name="Arc Of Montgomery County Inc",address="8961 S Central Expy",city="Trowutta",state="NS"},
                new Person { first_name="Iraida",last_name="Sionesini",company_name="Redington, Thomas P Esq",address="7 Wiley Post Way",city="Rouse Hill",state="QL"},
                new Person { first_name="Alona",last_name="Driesenga",company_name="Milwaukee Courier Inc",address="60 S 4th St",city="Wyandra",state="QL"},
                new Person { first_name="Lajuana",last_name="Vonderahe",company_name="Mervis Steel Co",address="6 Lafayette St #3034",city="Goondi Hill",state="WA"},
                new Person { first_name="Madelyn",last_name="Maestri",company_name="M Sorkin Sanford Associates",address="35 Jefferson Ave",city="Hill River",state="SA"},
                new Person { first_name="Louann",last_name="Susmilch",company_name="Low Country Kitchen & Bath",address="3492 88th St",city="Fairview Park",state="NS"},
                new Person { first_name="William",last_name="Devol",company_name="Spieker Properties",address="20 Sw 28th Ter",city="Bar Beach",state="TA"},
                new Person { first_name="Corazon",last_name="Grafenstein",company_name="Walker & Brehn Pa",address="6 Argyle Rd",city="University Of Tasmania",state="VI"},
                new Person { first_name="Fairy",last_name="Burket",company_name="U Stor",address="438 E Reynolds Rd #239",city="Regent West",state="QL"},
                new Person { first_name="Lashawn",last_name="Urion",company_name="Moorhead, Michael D Esq",address="47 Hall St",city="Oxley",state="TA"},
                new Person { first_name="Ronald",last_name="Gayner",company_name="R M Sloan Co Inc",address="17720 Beach Blvd",city="Don",state="VI"},
                new Person { first_name="Shizue",last_name="Hayduk",company_name="Star Limousine",address="8 2nd St",city="Nyora",state="QL"},
                new Person { first_name="Nida",last_name="Fitz",company_name="Pioneer Telephone Paging",address="490 Court St",city="Croydon",state="TA"},
                new Person { first_name="Amos",last_name="Limberg",company_name="Communication Buildings Amer",address="1456 Hill Rd",city="Scottsdale",state="VI"},
                new Person { first_name="Dexter",last_name="Prosienski",company_name="Components & Equipment Co",address="6 7th St",city="Montrose",state="VI"},
                new Person { first_name="Ludivina",last_name="Calamarino",company_name="Grand Rapids Right To Life",address="29 Nottingham Way #926",city="Oak Park",state="SA"},
                new Person { first_name="Ariel",last_name="Stavely",company_name="Martin Nighswander & Mitchell",address="8818 Century Park E #33",city="Nailsworth",state="QL"},
                new Person { first_name="Haley",last_name="Vaughn",company_name="Barter Systems Inc",address="4 Commerce Center Dr",city="Tarong",state="SA"},
                new Person { first_name="Raelene",last_name="Legeyt",company_name="W R Grace & Co",address="979 S La Cienega Blvd #627",city="Kensington Park",state="QL"},
                new Person { first_name="Micaela",last_name="Shiflett",company_name="Davis, J Mark Esq",address="9181 E 26th St",city="Ashmore",state="VI"},
                new Person { first_name="Alpha",last_name="Prudhomme",company_name="Roswell Honda Partners",address="8855 North Ave",city="Granya",state="VI"},
                new Person { first_name="Zack",last_name="Warman",company_name="Era Mclachlan John Morgan Real",address="4 Spinning Wheel Ln",city="Alexandra",state="SA"},
                new Person { first_name="Wilford",last_name="Pata",company_name="Vaughan, James J Esq",address="5905 S 32nd St",city="Wirrulla",state="TA"},
                new Person { first_name="Carman",last_name="Robasciotti",company_name="Wzyx 1440 Am",address="514 Glenn Way",city="Weymouth",state="NS"},
                new Person { first_name="Carylon",last_name="Bayot",company_name="Amercn Spdy Printg Ctrs Ocala",address="708 S Wilson Way",city="Summer Hill",state="QL"},
                new Person { first_name="Gladys",last_name="Schmale",company_name="A & D Pallet Co",address="16949 Harristown Rd",city="Shailer Park",state="NS"},
                new Person { first_name="Matilda",last_name="Peleg",company_name="Nationwide Insurance",address="9 13th Ave S",city="Bell",state="VI"},
                new Person { first_name="Jacklyn",last_name="Wojnar",company_name="Gallagher, Owen Esq",address="1 Rock Island Rd #8",city="Licola",state="WA"},

            };
            return Json(items, JsonRequestBehavior.AllowGet);
        }

    }
}